"""Auto-generated by catfish_freeze_skill (2026-05-13 17:52:05).

skill:        department/eis-checkout
description:  登录 EIS 后点下班打卡按钮
source trace: /Users/chenhongbo/.catfish/traces/session_eis-checkout_20260513_175146_430a7a.jsonl (3 steps)
frozen by:    BL-MM9-FREEZE (5/12 鸿波拍板, 教学→凝固管道)

# 这是凝固出来的 skill, 不是手写的

如果你 (员工 / LLM) 看 EIS / 业务流程的细节, 不要改 script.py — 走"再教一次"
路径让 catfish_freeze_skill 重新凝固. 手改容易跟下次凝固冲突.

# 执行模型

script 通过 catfish_tool_bridge.dispatch_native 调用原生 tool. 不自己开
Playwright — 复用 catfish_browser_* 内部已经写好的 CDP connect / secret_ref
resolve / SSRF deny / 等基础设施. 每 step 一次 dispatch.
"""
from __future__ import annotations

import logging
import time as _time
from typing import Any

logger = logging.getLogger("catfish.skill.eis_checkout")


def _call(tool_name: str, args: dict[str, Any], retries: int = 2, retry_delay: float = 2.5) -> dict[str, Any]:
    """走 catfish dispatch 调原生 tool. 返 result dict.

    BL-MM9-FREEZE-v2 schema 兼容 (5/12 鸿波撞坑发现): browser_* 工具用老 schema
    {"type": "ok/error", "error": "..."}, 没 `ok` 字段. freeze/recognize 等用
    新 schema {"ok": true/false, ...}. _call 同时认两种, 不让 schema 不匹配让
    script.py 把成功当失败 raise.

    cold-start fix: 失败时 sleep 2.5s 重试最多 2 次, 撑过 chrome / 模型 cold.
    """
    from catfish_tool_bridge.catfish_tools import dispatch_native  # noqa: PLC0415
    last_result: dict[str, Any] = {"ok": False, "error": "not attempted"}
    for attempt in range(retries + 1):
        try:
            r = dispatch_native(tool_name, args)
            if not isinstance(r, dict):
                return {"ok": True, "raw": r}
            # schema 兼容: 失败判定优先级:
            #  1) r["type"] == "error" → 失败 (browser_* 老 schema)
            #  2) r["ok"] is False → 失败 (新 schema)
            #  3) 否则 → 成功
            is_fail = (r.get("type") == "error") or (r.get("ok") is False)
            if not is_fail:
                # 成功 → 统一加 ok=True 给上游 script.py 用
                out = dict(r)
                out.setdefault("ok", True)
                return out
            last_result = dict(r)
            last_result.setdefault("ok", False)
            if not last_result.get("error"):
                last_result["error"] = f"{tool_name} 失败 (无 error 详情)"
        except Exception as e:
            last_result = {"ok": False, "error": f"{tool_name} 抛异常: {type(e).__name__}: {e!r}"}
        if attempt < retries:
            logger.info("_call retry %d/%d for %s: %s", attempt + 1, retries, tool_name, last_result.get("error", "?"))
            _time.sleep(retry_delay)
    return last_result


def render_eis_checkout(
    **_kwargs: Any,
) -> dict[str, Any]:
    """跑凝固后的 department/eis-checkout 流程.

    Returns: {ok, ...} 业务结果. 失败时 ok=false + error + last_step.
    """
    _started = _time.time()
    captcha_attempts = 0
    captcha_text = None
    last_step = None
    try:
        last_step = "run_skill:department/eis-login"
        _r = _call("catfish_run_skill", {"skill_path": 'department/eis-login', "params": {'username': 'chenhb'}})
        if not _r.get("ok"): raise _SkillStepFailure("run_skill:department/eis-login", _r.get("error", "嵌套 skill 失败"))
        # skip (LLM-only): catfish_browser_find_by_text
        last_step = "click:div.able"
        _r = _call("catfish_browser_click", {"selector": 'div.able'})
        if not _r.get("ok"): raise _SkillStepFailure("click", _r.get("error", "click 失败"))
        return {
            "ok": True,
            "captcha_attempts": captcha_attempts,
            "duration_ms": int((_time.time() - _started) * 1000),
        }
    except _SkillStepFailure as fail:
        logger.warning("skill step %s 失败: %s", fail.step, fail.message)
        return {
            "ok": False,
            "error": fail.message,
            "last_step": fail.step,
            "captcha_attempts": captcha_attempts,
            "duration_ms": int((_time.time() - _started) * 1000),
        }
    except Exception as e:
        logger.exception("skill 异常")
        return {
            "ok": False,
            "error": repr(e),
            "last_step": last_step,
            "captcha_attempts": captcha_attempts,
            "duration_ms": int((_time.time() - _started) * 1000),
        }


class _SkillStepFailure(Exception):
    def __init__(self, step: str, message: str) -> None:
        self.step = step
        self.message = message
        super().__init__(f"{step}: {message}")
