"""skill_freeze — BL-MM9-FREEZE (5/12 鸿波拍板) 教学→凝固管道.

# 闭环

  教学:   员工说"我教你"  → LLM agent 调 catfish_browser_* / recognize_captcha
          / browser_locate 一步步操作 → trace_recorder 自动写 jsonl
  凝固:   员工说"凝固成 skill" → catfish_freeze_skill(name='eis-login', ...)
          → 读 trace → 模板化生成 script.py + SKILL.md → 落到
          catfish/skills/<ns>/<name>/ → spawn install_to_hermes.sh 同步到
          ~/.hermes/skills/productivity/catfish-<name>/
  复用:   下次员工说"上 EIS 看待办" → LLM 看 system prompt 注入的 skill 列表
          → 调 catfish_run_skill('department/eis-login', {...}) → run_skill
          load script.py → 全套 Playwright 跑完 → 返结果

# 这模块只管"凝固"这一段

输入: name (e.g. 'eis-login'), namespace (默认 'department'), description,
trace_start / trace_end (时间区间, 默认最近 1 小时所有成功 trace)

输出: script.py + SKILL.md + 副作用 (install_to_hermes 同步)

# 模板化逻辑 (朴素 + 务实 MVP)

| trace tool                       | script.py 行                                                         |
|----------------------------------|---------------------------------------------------------------------|
| catfish_browser_goto(url)        | page.goto(url, wait_until="load")                                   |
| catfish_browser_snapshot(...)    | (跳过 — snapshot 是给 LLM 看 DOM 用的, script 不需要)                 |
| catfish_browser_screenshot(...)  | (跳过)                                                              |
| catfish_browser_find_by_text(...)| (跳过 — selector 在 trace 里下一个 fill/click 已经带, 不再 find)     |
| catfish_browser_fill(sel, text)  | page.fill(sel, text)  [若 args 有 secret_ref → resolve_secret 调用] |
| catfish_browser_fill(#captcha,T) | T 若来自上一个 recognize_captcha 的 result.text → 改成实时调用       |
| catfish_browser_click(selector)  | page.click(selector)                                                |
| catfish_browser_click(coords=...)| page.mouse.click(x, y)                                              |
| catfish_recognize_captcha(...)   | retry loop {recognize_captcha_sync(...) if conf >= 0.6 break else click(#captchaImg)} |
| catfish_browser_locate(...)      | (跳过 — locate 是视觉定位用的, 留 selector 给后续 click 用)          |

# 数据流依赖解析

最关键: `fill('#captcha', 'cT92')` 里的 'cT92' 是上一个 recognize_captcha
result 的 text. trace 里这俩动作连着 → freeze 引擎识别 → 改成实时调用,
不 hard-code 'cT92' (那是临时验证码值).

# 不让 LLM 介入

凝固过程**纯模板**, 不让 LLM 写代码 — 不然又把不确定性引回来.

# 字段映射规则

  secret_ref 字段 → script.py 用 resolve_secret(...)
  其它字段 → 当 skill 参数 (用户名 / 等), 通过 render_<name>(...) 入参传

# 失败约束

  - trace 里有 ok=false 的步骤 → 不能凝固 (整个 trace 视为失败教学)
  - tool 类型未识别 → 跳过 + warn
  - secret_ref 检测失败 (e.g. 是明文密码 in args.text) → 拒绝凝固, 防把
    明文密码写进 script.py
"""
from __future__ import annotations

import logging
import re
import subprocess
import time
from pathlib import Path
from typing import Any

from . import trace_recorder

logger = logging.getLogger("catfish.tool_bridge.skill_freeze")

#: catfish 工程 skills 根目录解析跟 catfish_run_skill 同源
def _resolve_catfish_skills_root() -> Path | None:
    import os  # noqa: PLC0415
    env_dir = os.environ.get("CATFISH_SKILLS_DIR")
    if env_dir:
        p = Path(env_dir).expanduser()
        if p.is_dir():
            return p
    # 常见路径
    candidates = [
        Path.home() / "person_task" / "catfish" / "skills",
        Path.home() / "catfish" / "skills",
        Path(__file__).resolve().parent.parent.parent.parent.parent / "skills",
    ]
    for c in candidates:
        if c.is_dir():
            return c
    return None


# ─── 模板片段 ────────────────────────────────────────────────────────


_SCRIPT_HEADER = '''"""Auto-generated by catfish_freeze_skill ({frozen_at}).

skill:        {namespace}/{name}
description:  {description}
source trace: {trace_path} ({step_count} steps)
frozen by:    BL-MM9-FREEZE (5/12 鸿波拍板, 教学→凝固管道)

# 这是凝固出来的 skill, 不是手写的

如果你 (员工 / LLM) 看 EIS / 业务流程的细节, 不要改 script.py — 走"再教一次"
路径让 catfish_freeze_skill 重新凝固. 手改容易跟下次凝固冲突.

# 执行模型

script 通过 catfish_tool_bridge.dispatch_native 调用原生 tool. 不自己开
Playwright — 复用 catfish_browser_* 内部已经写好的 CDP connect / secret_ref
resolve / SSRF deny / 等基础设施. 每 step 一次 dispatch.
"""
from __future__ import annotations

import logging
import time as _time
from typing import Any

logger = logging.getLogger("catfish.skill.{name_slug}")


def _call(tool_name: str, args: dict[str, Any], retries: int = 2, retry_delay: float = 2.5) -> dict[str, Any]:
    """走 catfish dispatch 调原生 tool. 返 result dict.

    BL-MM9-FREEZE cold-start fix (5/12): 第一次跑 skill 时 chrome / 上游 LLM
    都可能 cold, 第一步 goto 撞冷启动失败. _call 自带 retry — 失败时 sleep
    后重试, 把 cold start 期间撑过去.
    """
    from catfish_tool_bridge.catfish_tools import dispatch_native  # noqa: PLC0415
    last_result: dict[str, Any] = {{"ok": False, "error": "not attempted"}}
    for attempt in range(retries + 1):
        try:
            r = dispatch_native(tool_name, args)
            if not isinstance(r, dict):
                return {{"ok": True, "raw": r}}
            # 成功 → 立即返
            if r.get("ok", True):
                return r
            last_result = r
        except Exception as e:
            last_result = {{"ok": False, "error": repr(e)}}
        if attempt < retries:
            logger.info("_call retry %d/%d for %s: %s", attempt + 1, retries, tool_name, last_result.get("error", "?"))
            _time.sleep(retry_delay)
    return last_result


def render_{fn_name}(
{params_block}    **_kwargs: Any,
) -> dict[str, Any]:
    """跑凝固后的 {namespace}/{name} 流程.

    Returns: {{ok, ...}} 业务结果. 失败时 ok=false + error + last_step.
    """
    _started = _time.time()
    captcha_attempts = 0
    captcha_text = None
    last_step = None
    try:
'''

_SCRIPT_FOOTER = '''
        return {
            "ok": True,
            "captcha_attempts": captcha_attempts,
            "duration_ms": int((_time.time() - _started) * 1000),
        }
    except _SkillStepFailure as fail:
        logger.warning("skill step %s 失败: %s", fail.step, fail.message)
        return {
            "ok": False,
            "error": fail.message,
            "last_step": fail.step,
            "captcha_attempts": captcha_attempts,
            "duration_ms": int((_time.time() - _started) * 1000),
        }
    except Exception as e:
        logger.exception("skill 异常")
        return {
            "ok": False,
            "error": repr(e),
            "last_step": last_step,
            "captcha_attempts": captcha_attempts,
            "duration_ms": int((_time.time() - _started) * 1000),
        }


class _SkillStepFailure(Exception):
    def __init__(self, step: str, message: str) -> None:
        self.step = step
        self.message = message
        super().__init__(f"{step}: {message}")
'''


_CAPTCHA_RETRY_BLOCK = '''
        # captcha retry loop (freeze 引擎自动插入: 识别失败时刷图重识)
        last_step = "captcha_recognize"
        captcha_text = None
        for _attempt in range(max_captcha_retry):
            captcha_attempts += 1
            _r = _call("catfish_recognize_captcha", {{"selector": {captcha_selector!r}, "hint": {hint!r}}})
            if _r.get("ok") and _r.get("confidence", 0) >= 0.6:
                captcha_text = _r.get("text", "")
                break
            # 刷新验证码图
            _call("catfish_browser_click", {{"selector": {captcha_selector!r}}})
            _time.sleep(0.5)
        if not captcha_text:
            raise _SkillStepFailure("captcha_recognize", "验证码识别失败超过 max_captcha_retry 次")
'''


# ─── 数据流依赖解析 ──────────────────────────────────────────────────


_CAPTCHA_SELECTORS = ("#captcha", "input[name=captcha]", "input[name=vcode]")


def _is_captcha_fill(args: dict, prev_captcha_result: dict | None) -> bool:
    """fill 的 selector 是验证码框 + text 跟上一个 recognize_captcha 一致?"""
    sel = (args.get("selector") or "").strip()
    text = (args.get("text") or "").strip()
    if not sel or not text:
        return False
    if not any(s in sel for s in _CAPTCHA_SELECTORS):
        return False
    if prev_captcha_result is None:
        return False
    return prev_captcha_result.get("text", "").strip() == text


def _looks_like_password(args: dict) -> bool:
    """启发: text 字段像明文密码 (8-32 字 + 含数字/符号)? 拒绝凝固保护."""
    text = args.get("text")
    if not isinstance(text, str):
        return False
    # secret_ref 形态明确不是明文
    if "secret_ref" in args and args.get("secret_ref"):
        return False
    # 启发: 8-32 字符 + 含数字 + 含字母 = 像密码
    if 8 <= len(text) <= 32 and re.search(r"\d", text) and re.search(r"[A-Za-z]", text):
        # 但也可能是验证码 / 用户名. 加一个进 selector 判断 — 只有 #pwd 等
        # 密码框 selector 才算密码
        sel = (args.get("selector") or "").lower()
        if any(s in sel for s in ("#pwd", "[name=password]", "[type=password]", "password")):
            return True
    return False


# ─── 模板化主流程 ────────────────────────────────────────────────────


def _quote_str(s: str) -> str:
    """python 字符串字面量, escape 引号."""
    return repr(s)


def _emit_step(step: dict, prev_captcha_result: dict | None) -> tuple[list[str], dict | None]:
    """单个 trace step 模板化成 python 行(s).

    Returns: (lines, new_prev_captcha_result). new_prev 用于下一 step 判断
    captcha 数据流.
    """
    tool = step.get("tool")
    args = step.get("args") or {}
    result = step.get("result") or {}

    # 跳过类: snapshot / screenshot / find_by_text / locate 是"给 LLM 看"的
    if tool in {
        "catfish_browser_snapshot",
        "catfish_browser_screenshot",
        "catfish_browser_find_by_text",
        "catfish_browser_locate",
    }:
        return [f"        # skip (LLM-only): {tool}"], prev_captcha_result

    # goto
    if tool == "catfish_browser_goto":
        url = args.get("url") or ""
        wait_until = args.get("wait_until") or "load"
        return [
            f'        last_step = "goto:{url}"',
            f'        _r = _call("catfish_browser_goto", {{"url": {_quote_str(url)}, "wait_until": {_quote_str(wait_until)}}})',
            f'        if not _r.get("ok"): raise _SkillStepFailure("goto", _r.get("error", "goto 失败"))',
        ], prev_captcha_result

    # captcha 识别 — 用 retry loop 代替单次调用
    if tool == "catfish_recognize_captcha":
        selector = args.get("selector") or "#captchaImg"
        hint = args.get("hint") or "alphanumeric_4"
        block = _CAPTCHA_RETRY_BLOCK.format(
            captcha_selector=selector, hint=hint
        )
        # 记 result 给下一步 fill 判断
        new_prev = result if isinstance(result, dict) else None
        return [block], new_prev

    # fill
    if tool == "catfish_browser_fill":
        selector = args.get("selector") or ""
        # secret_ref 路径 — 把 secret_ref 透传给 catfish_browser_fill,
        # 它内部用 secret_resolver.resolve_secret(ref) 把 keychain://xxx 解析成明文
        # 喂给 page.fill, 明文不进 LLM 上下文也不进 script 字面量
        if args.get("secret_ref"):
            sref = args["secret_ref"]
            return [
                f'        last_step = "fill_secret:{selector}"',
                f'        _r = _call("catfish_browser_fill", {{"selector": {_quote_str(selector)}, "secret_ref": password_ref}})',
                f'        if not _r.get("ok"): raise _SkillStepFailure("fill_secret", _r.get("error", "fill 失败"))',
            ], prev_captcha_result
        # 明文密码 — 拒绝
        if _looks_like_password(args):
            return [
                f'        # SECURITY: refused — args 含明文密码 (selector={selector}).',
                f'        raise RuntimeError("refused to bake plaintext password")',
            ], prev_captcha_result
        # captcha 字段 — 用上一步识别结果
        if _is_captcha_fill(args, prev_captcha_result):
            return [
                f'        last_step = "fill_captcha:{selector}"',
                f'        _r = _call("catfish_browser_fill", {{"selector": {_quote_str(selector)}, "text": captcha_text}})',
                f'        if not _r.get("ok"): raise _SkillStepFailure("fill_captcha", _r.get("error", "fill 失败"))',
            ], prev_captcha_result
        # 普通 text fill (username 走这条, 把 text 抽成参数 username 而不是 hard-code)
        text = args.get("text", "")
        sel_l = selector.lower()
        is_username = any(c in sel_l for c in ("#name", "[name=username]", "username"))
        text_repr = "username" if is_username else _quote_str(text)
        return [
            f'        last_step = "fill:{selector}"',
            f'        _r = _call("catfish_browser_fill", {{"selector": {_quote_str(selector)}, "text": {text_repr}}})',
            f'        if not _r.get("ok"): raise _SkillStepFailure("fill", _r.get("error", "fill 失败"))',
        ], prev_captcha_result

    # click
    if tool == "catfish_browser_click":
        coords = args.get("coordinates")
        if isinstance(coords, (list, tuple)) and len(coords) == 2:
            x, y = coords
            return [
                f'        last_step = "click_coords:{x},{y}"',
                f'        _r = _call("catfish_browser_click", {{"coordinates": [{x}, {y}]}})',
                f'        if not _r.get("ok"): raise _SkillStepFailure("click_coords", _r.get("error", "click 失败"))',
            ], prev_captcha_result
        selector = args.get("selector") or ""
        return [
            f'        last_step = "click:{selector}"',
            f'        _r = _call("catfish_browser_click", {{"selector": {_quote_str(selector)}}})',
            f'        if not _r.get("ok"): raise _SkillStepFailure("click", _r.get("error", "click 失败"))',
        ], prev_captcha_result

    return [f'        # unhandled tool: {tool}'], prev_captcha_result


def _infer_params(trace: list[dict]) -> list[tuple[str, str, str]]:
    """从 trace 推参数列表.

    Returns: [(name, type, default), ...]
    """
    params: list[tuple[str, str, str]] = []
    seen_secret_refs: set[str] = set()
    # username 启发: 第一个非密码 / 非验证码 fill 的 text → 当成 username
    has_username = False
    has_captcha = False
    for step in trace:
        if step.get("tool") != "catfish_browser_fill":
            if step.get("tool") == "catfish_recognize_captcha":
                has_captcha = True
            continue
        args = step.get("args") or {}
        if args.get("secret_ref"):
            sref = args.get("secret_ref", "")
            if sref not in seen_secret_refs:
                seen_secret_refs.add(sref)
                params.append(
                    ("password_ref", "str", _quote_str(sref))
                )
        elif not has_username:
            sel = (args.get("selector") or "").lower()
            text = args.get("text", "")
            if not any(c in sel for c in ("captcha", "vcode", "pwd", "password")):
                # 当 username 参数
                params.append(("username", "str", _quote_str(text)))
                has_username = True
    if has_captcha:
        params.append(("max_captcha_retry", "int", "3"))
    return params


def _format_params_block(params: list[tuple[str, str, str]]) -> str:
    """params → python 参数声明 block."""
    if not params:
        return ""
    lines = []
    for name, type_, default in params:
        lines.append(f"    {name}: {type_} = {default},")
    return "\n".join(lines) + "\n"


# ─── SKILL.md 生成 ──────────────────────────────────────────────────


_SKILL_MD_TEMPLATE = '''---
name: {name}
version: "0.1.0-frozen"
deprecated: false
description: |-
  ⭐ {description}

  ⚙️ 由 catfish_freeze_skill 自动凝固 ({frozen_at}, BL-MM9-FREEZE).
  源 trace: {trace_path} (steps {step_start}-{step_end}, ok={ok_count}/{total_count}).
  **不要手改 script.py** — 业务流程变了走"再教一次"路径让管道重新凝固.

  调用入口: `render_{fn_name}({param_names})` (script.py).
---

# {name} — {description}

> 凝固于 {frozen_at}. 教学→凝固→复用闭环 (BL-MM9-FREEZE).

## 怎么调

```
catfish_run_skill(
  skill_path="{namespace}/{name}",
  params={{{example_params}}}
)
```

## 凝固时的 8 步教学 trace

{trace_summary}

## 参数

{params_table}

## 修改方式

**不要直接改 script.py**. 业务流程变化 (页面改版 / 加新步骤) → 走"再教一次":

  1. 员工: "再教一次 {name}, 改的地方是 ..."
  2. LLM agent 跑新流程, trace_recorder 自动记
  3. 员工: "凝固成 v2"
  4. `catfish_freeze_skill(name="{name}", overwrite=true)`

凝固管道会重新生成 script.py + SKILL.md, 覆盖本份.

## 已知限制 (5/12 MVP)

- 凝固只看顺序, 不解 trace 里的"如果 X 则 Y"分支. 业务有分支 → 拆成多个 skill.
- 等待逻辑: 每个 click / goto 后默认 networkidle wait, 5s 超时.
- captcha retry 是自动插入 (识别 confidence < 0.6 时刷图重识), 不靠 trace.
- secret_ref 必须在教学时就用 keychain://, 不接受明文密码凝固.
'''


def _build_skill_md(
    name: str,
    namespace: str,
    description: str,
    fn_name: str,
    trace: list[dict],
    trace_path: str,
    step_start: int,
    step_end: int,
    ok_count: int,
    total_count: int,
    params: list[tuple[str, str, str]],
) -> str:
    """渲染 SKILL.md."""
    trace_summary_lines = []
    for i, step in enumerate(trace, 1):
        tool = step.get("tool")
        args = step.get("args") or {}
        sel = args.get("selector") or args.get("url") or ""
        if sel:
            trace_summary_lines.append(f"  {i}. `{tool}({sel})`")
        else:
            trace_summary_lines.append(f"  {i}. `{tool}(...)`")
    params_table_rows = []
    param_names_inline = []
    example_params_parts = []
    for n, t, d in params:
        params_table_rows.append(f"| `{n}` | {t} | {d} |")
        param_names_inline.append(n)
        example_params_parts.append(f'"{n}": {d}')
    if params_table_rows:
        params_table = "| 参数 | 类型 | 默认 |\n|---|---|---|\n" + "\n".join(params_table_rows)
    else:
        params_table = "_(无参数)_"
    return _SKILL_MD_TEMPLATE.format(
        name=name,
        namespace=namespace,
        description=description,
        frozen_at=time.strftime("%Y-%m-%d %H:%M:%S"),
        trace_path=trace_path,
        step_start=step_start,
        step_end=step_end,
        ok_count=ok_count,
        total_count=total_count,
        fn_name=fn_name,
        trace_summary="\n".join(trace_summary_lines),
        params_table=params_table,
        param_names=", ".join(param_names_inline),
        example_params=", ".join(example_params_parts),
    )


# ─── 主入口 ──────────────────────────────────────────────────────────


def _slugify(s: str) -> str:
    """name → python identifier safe."""
    return re.sub(r"[^a-z0-9_]+", "_", s.lower()).strip("_") or "skill"


def freeze_skill(args: dict[str, Any]) -> dict[str, Any]:
    """tool entry: catfish_freeze_skill.

    args:
      name: str, e.g. "eis-login"
      namespace: str, default "department"
      description: str
      trace_since_unix: float | None — 起始时间, None=最近 1 小时
      trace_until_unix: float | None — 截止时间
      overwrite: bool — 已存在的 skill 是否覆盖. 默认 false
      run_install: bool — 凝固后是否自动跑 install_to_hermes.sh. 默认 true
    """
    name = (args.get("name") or "").strip()
    if not name or not re.match(r"^[a-z][a-z0-9\-]*$", name):
        return {
            "ok": False,
            "error": "name 必填, 小写字母 / 数字 / 横线, 必须字母开头 (例 'eis-login')",
        }
    namespace = (args.get("namespace") or "department").strip()
    if namespace not in ("department", "personal", "team"):
        return {
            "ok": False,
            "error": f"namespace 必须是 department / personal / team, 不接受 {namespace!r}",
        }
    description = (args.get("description") or f"凝固 {name} 流程").strip()[:500]

    since = args.get("trace_since_unix")
    until = args.get("trace_until_unix")
    if since is None:
        since = time.time() - 3600  # 默认最近 1 小时
    overwrite = bool(args.get("overwrite", False))
    run_install = bool(args.get("run_install", True))

    # 1) 读 trace
    trace = trace_recorder.read_traces(
        since_unix=since, until_unix=until, only_ok=True
    )
    if not trace:
        return {
            "ok": False,
            "error": (
                f"trace 为空 (since={since}, until={until}). 教学时是不是没调"
                f"任何 catfish_browser_* / recognize_captcha? "
                f"调 catfish_freeze_inspect 看 trace 状态."
            ),
        }
    # 排序
    trace.sort(key=lambda x: x.get("seq", 0))

    # 2) 解析 + 模板化
    params = _infer_params(trace)
    fn_name = _slugify(name)
    body_lines: list[str] = []
    prev_captcha = None
    for step in trace:
        lines, prev_captcha = _emit_step(step, prev_captcha)
        body_lines.extend(lines)

    # 安全检查: body 里如果出现 'refused to bake plaintext password' → 中止
    if any("refused to bake plaintext password" in line for line in body_lines):
        return {
            "ok": False,
            "error": (
                "trace 含明文密码 fill. 拒绝凝固. 教学时改用 "
                "catfish_browser_fill(selector='#pwd', secret_ref='keychain://xxx') "
                "再 freeze."
            ),
        }

    # 3) 落地
    root = _resolve_catfish_skills_root()
    if root is None:
        return {
            "ok": False,
            "error": "找不到 catfish skills 根目录 (设 CATFISH_SKILLS_DIR env).",
        }
    skill_dir = root / namespace / name
    if skill_dir.exists() and not overwrite:
        return {
            "ok": False,
            "error": (
                f"skill 已存在: {skill_dir}. 用 overwrite=true 覆盖, "
                f"或换 name."
            ),
        }
    skill_dir.mkdir(parents=True, exist_ok=True)

    script_py = _SCRIPT_HEADER.format(
        frozen_at=time.strftime("%Y-%m-%d %H:%M:%S"),
        namespace=namespace,
        name=name,
        name_slug=fn_name,
        fn_name=fn_name,
        description=description,
        trace_path=str(trace_recorder.TRACE_PATH),
        step_count=len(trace),
        params_block=_format_params_block(params),
    ) + "\n".join(body_lines) + _SCRIPT_FOOTER

    (skill_dir / "script.py").write_text(script_py, encoding="utf-8")

    skill_md = _build_skill_md(
        name=name,
        namespace=namespace,
        description=description,
        fn_name=fn_name,
        trace=trace,
        trace_path=str(trace_recorder.TRACE_PATH),
        step_start=trace[0].get("seq", 0),
        step_end=trace[-1].get("seq", 0),
        ok_count=sum(1 for x in trace if x.get("ok")),
        total_count=len(trace),
        params=params,
    )
    (skill_dir / "SKILL.md").write_text(skill_md, encoding="utf-8")

    # 4) install_to_hermes
    install_result: dict[str, Any] = {"ran": False}
    if run_install:
        install_sh = root / "install_to_hermes.sh"
        if install_sh.exists():
            try:
                proc = subprocess.run(
                    ["bash", str(install_sh)],
                    capture_output=True, text=True, timeout=30,
                )
                install_result = {
                    "ran": True,
                    "returncode": proc.returncode,
                    "stdout_tail": proc.stdout[-500:] if proc.stdout else "",
                    "stderr_tail": proc.stderr[-500:] if proc.stderr else "",
                }
            except Exception as e:
                install_result = {"ran": True, "error": repr(e)}
        else:
            install_result = {"ran": False, "reason": "install_to_hermes.sh 不存在"}

    return {
        "ok": True,
        "name": name,
        "namespace": namespace,
        "skill_path": f"{namespace}/{name}",
        "hermes_name": f"catfish-{name}",
        "files": [
            str(skill_dir / "script.py"),
            str(skill_dir / "SKILL.md"),
        ],
        "trace_steps_used": len(trace),
        "params": [{"name": n, "type": t, "default": d} for n, t, d in params],
        "install": install_result,
        "summary": (
            f"✓ 凝固完成. {namespace}/{name} (script.py + SKILL.md). "
            f"调 catfish_run_skill('{namespace}/{name}', {{...}}) 复用. "
            f"hermes 端 = catfish-{name}."
        ),
    }


def freeze_inspect(args: dict[str, Any]) -> dict[str, Any]:
    """tool entry: catfish_freeze_inspect — 看 trace 状态, 决定能不能凝固."""
    summary = trace_recorder.session_summary()
    since = args.get("since_unix")
    if since is None:
        since = time.time() - 3600
    trace = trace_recorder.read_traces(since_unix=since, only_ok=True)
    return {
        "ok": True,
        "trace_file": summary,
        "recent_steps_in_window": len(trace),
        "recent_steps_summary": [
            {
                "seq": x.get("seq"),
                "tool": x.get("tool"),
                "args_keys": list((x.get("args") or {}).keys()),
                "ts": x.get("ts"),
            }
            for x in trace[-30:]
        ],
        "summary": (
            f"trace 文件 {summary.get('lines', 0)} 行, 最近 1 小时内 "
            f"{len(trace)} 步成功. 调 catfish_freeze_skill(name=..., "
            f"description=...) 凝固."
        ),
    }


def freeze_rotate(args: dict[str, Any]) -> dict[str, Any]:
    """tool entry: catfish_freeze_rotate — 凝固完后清空 active trace."""
    reason = (args.get("reason") or "post-freeze").strip()
    archive = trace_recorder.rotate(reason=reason)
    return {
        "ok": bool(archive),
        "archived_to": archive,
        "summary": (
            f"trace 已 rotate 到 {archive}." if archive
            else "trace 为空, 没东西 rotate."
        ),
    }


__all__ = ["freeze_skill", "freeze_inspect", "freeze_rotate"]
