"""Auto-generated by catfish_freeze_skill (2026-05-12 13:26:39).

skill:        department/eis-login
description:  登录 EIS 一站式信息门户（更新 URL 为 http://eis.ffcs.cn，支持验证码自动识别）
source trace: /Users/chenhongbo/.catfish/traces/session_eis-login_20260512_131432_c7a2a9.jsonl (7 steps)
frozen by:    BL-MM9-FREEZE (5/12 鸿波拍板, 教学→凝固管道)

# 这是凝固出来的 skill, 不是手写的

如果你 (员工 / LLM) 看 EIS / 业务流程的细节, 不要改 script.py — 走"再教一次"
路径让 catfish_freeze_skill 重新凝固. 手改容易跟下次凝固冲突.

# 执行模型

script 通过 catfish_tool_bridge.dispatch_native 调用原生 tool. 不自己开
Playwright — 复用 catfish_browser_* 内部已经写好的 CDP connect / secret_ref
resolve / SSRF deny / 等基础设施. 每 step 一次 dispatch.
"""
from __future__ import annotations

import logging
import time as _time
from typing import Any

logger = logging.getLogger("catfish.skill.eis_login")


def _call(tool_name: str, args: dict[str, Any], retries: int = 2, retry_delay: float = 2.5) -> dict[str, Any]:
    """走 catfish dispatch 调原生 tool. 返 result dict.

    BL-MM9-FREEZE-v2 schema 兼容 (5/12 鸿波撞坑发现): browser_* 工具用老 schema
    {"type": "ok/error", "error": "..."}, 没 `ok` 字段. freeze/recognize 等用
    新 schema {"ok": true/false, ...}. _call 同时认两种, 不让 schema 不匹配让
    script.py 把成功当失败 raise.

    cold-start fix: 失败时 sleep 2.5s 重试最多 2 次, 撑过 chrome / 模型 cold.
    """
    from catfish_tool_bridge.catfish_tools import dispatch_native  # noqa: PLC0415
    last_result: dict[str, Any] = {"ok": False, "error": "not attempted"}
    for attempt in range(retries + 1):
        try:
            r = dispatch_native(tool_name, args)
            if not isinstance(r, dict):
                return {"ok": True, "raw": r}
            # schema 兼容: 失败判定优先级:
            #  1) r["type"] == "error" → 失败 (browser_* 老 schema)
            #  2) r["ok"] is False → 失败 (新 schema)
            #  3) 否则 → 成功
            is_fail = (r.get("type") == "error") or (r.get("ok") is False)
            if not is_fail:
                # 成功 → 统一加 ok=True 给上游 script.py 用
                out = dict(r)
                out.setdefault("ok", True)
                return out
            last_result = dict(r)
            last_result.setdefault("ok", False)
            if not last_result.get("error"):
                last_result["error"] = f"{tool_name} 失败 (无 error 详情)"
        except Exception as e:
            last_result = {"ok": False, "error": f"{tool_name} 抛异常: {type(e).__name__}: {e!r}"}
        if attempt < retries:
            logger.info("_call retry %d/%d for %s: %s", attempt + 1, retries, tool_name, last_result.get("error", "?"))
            _time.sleep(retry_delay)
    return last_result


def render_eis_login(
    username: str = 'chenhb',
    max_captcha_retry: int = 3,
    **_kwargs: Any,
) -> dict[str, Any]:
    # password_ref 8/20 删掉 —— 密码改走 secret_for_site (按当前页站点现查)。
    # 老调用方传 password_ref 不会炸: 它落进 **_kwargs 被忽略。
    #   · run_skill 是 fn(**params) 展开调的
    #   · SKILL.md 的示例也一并改了, 但对话历史里可能还留着老写法
    """跑凝固后的 department/eis-login 流程.

    Returns: {ok, ...} 业务结果. 失败时 ok=false + error + last_step.
    """
    _started = _time.time()
    captcha_attempts = 0
    captcha_text = None
    last_step = None
    try:
        last_step = "goto:http://eis.ffcs.cn"
        _r = _call("catfish_browser_goto", {"url": 'http://eis.ffcs.cn', "wait_until": 'load'})
        if not _r.get("ok"): raise _SkillStepFailure("goto", _r.get("error", "goto 失败"))
        # skip (LLM-only): catfish_browser_snapshot
        last_step = "fill:#name"
        _r = _call("catfish_browser_fill", {"selector": '#name', "text": username})
        if not _r.get("ok"): raise _SkillStepFailure("fill", _r.get("error", "fill 失败"))
        # 8/20 手改这一行 (破例, 理由见下)。改前是:
        #     _call("catfish_browser_fill", {"selector": '#pwd', "secret_ref": password_ref})
        # password_ref 默认焊的是 'keychain://eis_password' —— 4/28 手工建的那条。
        # 而员工现在改密码走 Companion 界面, 存的是 catfish-teaching:eis.ffcs.cn。
        # 8/20 比过两条的 sha256: **不一样**, 冻结 skill 拿的是过期密码, 登录会报
        # "账号或密码错误", 而界面上显示"已保存" —— 两边谁也不知道谁。
        #
        # 这个病 skill_freeze_template.py:175-190 早就写着 (8/17 实撞), 修法也在
        # 那儿: secret_for_site 不焊任何"当天的值", 站点是运行时从 page.url 取的,
        # 员工改完密码下一次跑就是新的。
        #
        # 本 skill 5/12 凝固, 比 secret_for_site (8/18 才加) 早三个月 —— 不是坏了,
        # 是生得早。
        #
        # 破例手改的理由: 这三行跟 skill_freeze_template.py 的 secret_for_site 分支
        # 生成的**逐字一致** (含 last_step 名字和两行 raise 的换行), 所以将来真重新
        # 凝固也会生成同一段, 不冲突。
        last_step = "fill_secret_for_site:#pwd"
        _r = _call("catfish_browser_fill", {"selector": '#pwd', "secret_for_site": True})
        if not _r.get("ok"):
            raise _SkillStepFailure("fill_secret_for_site", _r.get("error", "fill 失败"))

        # captcha retry loop (freeze 引擎自动插入: 识别失败时刷图重识)
        last_step = "captcha_recognize"
        captcha_text = None
        for _attempt in range(max_captcha_retry):
            captcha_attempts += 1
            _r = _call("catfish_recognize_captcha", {"selector": '#captchaImg', "hint": 'alphanumeric_4'})
            if _r.get("ok") and _r.get("confidence", 0) >= 0.6:
                captcha_text = _r.get("text", "")
                break
            # 刷新验证码图
            _call("catfish_browser_click", {"selector": '#captchaImg'})
            _time.sleep(0.5)
        if not captcha_text:
            raise _SkillStepFailure("captcha_recognize", "验证码识别失败超过 max_captcha_retry 次")

        last_step = "fill_captcha:#captcha"
        _r = _call("catfish_browser_fill", {"selector": '#captcha', "text": captcha_text})
        if not _r.get("ok"): raise _SkillStepFailure("fill_captcha", _r.get("error", "fill 失败"))
        last_step = "click:div.button-login"
        _r = _call("catfish_browser_click", {"selector": 'div.button-login'})
        if not _r.get("ok"): raise _SkillStepFailure("click", _r.get("error", "click 失败"))
        return {
            "ok": True,
            "captcha_attempts": captcha_attempts,
            "duration_ms": int((_time.time() - _started) * 1000),
        }
    except _SkillStepFailure as fail:
        logger.warning("skill step %s 失败: %s", fail.step, fail.message)
        return {
            "ok": False,
            "error": fail.message,
            "last_step": fail.step,
            "captcha_attempts": captcha_attempts,
            "duration_ms": int((_time.time() - _started) * 1000),
        }
    except Exception as e:
        logger.exception("skill 异常")
        return {
            "ok": False,
            "error": repr(e),
            "last_step": last_step,
            "captcha_attempts": captcha_attempts,
            "duration_ms": int((_time.time() - _started) * 1000),
        }


class _SkillStepFailure(Exception):
    def __init__(self, step: str, message: str) -> None:
        self.step = step
        self.message = message
        super().__init__(f"{step}: {message}")
