"""蒸馏节流 —— 24h cooldown 和"上次跑到哪了"。

8/15 从 catfish_memory_helpers.py 搬出来。

# 为什么要 cooldown

蒸馏是把散落的 journal / wiki 材料压成长期记忆, 一次要跑好几轮 LLM。没有
24h 闸的话, 同一次会话里连着触发几次, 既烧 token 又会把同样的内容反复写进
记忆。这个数跟老 gateway 的 memory_distill 保持一致 —— 两边不一致的话,
迁移期间会出现"同一件事在新旧两套里各记一遍"。
"""

from __future__ import annotations

import json
import time
from pathlib import Path
from typing import Any, Dict

try:
    from .catfish_memory_base import _DISTILL_COOLDOWN_SECONDS, logger
except ImportError:  # 独立脚本模式 (无父包)
    from catfish_memory_base import _DISTILL_COOLDOWN_SECONDS, logger



def _should_run_distill(catfish_home: Path) -> bool:
    """24h 内跑过 → False (不再跑). 没跑过 / 已超 24h → True."""
    state_path = catfish_home / "memory_distill_state.json"
    if not state_path.exists():
        return True
    try:
        state = json.loads(state_path.read_text(encoding="utf-8"))
        last = state.get("last_run_ts", 0)
        return (time.time() - last) >= _DISTILL_COOLDOWN_SECONDS
    except (OSError, ValueError, json.JSONDecodeError):
        return True


def _mark_distill_run(catfish_home: Path) -> None:
    """写 memory_distill_state.json 记录这次跑过."""
    state_path = catfish_home / "memory_distill_state.json"
    state_path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "last_run_ts": time.time(),
        "last_run_iso": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "source": "catfish-memory-plugin",
    }
    try:
        state_path.write_text(json.dumps(payload), encoding="utf-8")
    except OSError as e:
        logger.warning("写 memory_distill_state.json 失败: %s", e)


def _write_distilled(catfish_home: Path, text: str) -> None:
    """覆盖写 distilled_facts.md (跟老 gateway memory_distill.write_distilled_facts 等价)."""
    path = catfish_home / "distilled_facts.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    header = (
        f"<!-- Generated by catfish-memory plugin at "
        f"{time.strftime('%Y-%m-%d %H:%M:%S')} -->\n"
        f"<!-- on_session_end 触发, 来源 catfish-memory plugin -->\n\n"
    )
    try:
        path.write_text(header + text.strip() + "\n", encoding="utf-8")
    except OSError as e:
        logger.warning("写 distilled_facts.md 失败: %s", e)

